### ISSUE TITLE
Is there a way to get the prediction list only? and not run the specs?

### ISSUE THREAD

**Issue by noralin** [pluff/crystalball#100]
Can I do something like `bundle exec crystalball --list-only` and have the prediction list returned?

**Comment by pluff** [comment]
It's not supported out of the box. You can create your own script based on [PredictionBuilder](https://github.com/toptal/crystalball/blob/master/lib/crystalball/rspec/prediction_builder.rb) logic

**Comment by noralin** [comment]
make sense, thanks!
