### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by loadkpi** [pluff/crystalball#109]
Hello guys,

Thanks for your work.

Any plan to release a new version on RubyGem? The last few commits has some fixes that can be useful.

**Comment by ghost** [comment]
+1 require 'forwardable' stopped us for a bit

**Comment by pirj** [comment]
Just released [0.7.0](https://rubygems.org/gems/crystalball/versions/0.7.0) with all the latest changes.
Sorry for the delay.
