### ISSUE TITLE
Syntax error in setup docs (fixed, but not on website)

### ISSUE THREAD

**Issue by erikdstock** [pluff/crystalball#122]
It looks like a fix from 8 months ago never made it into the built site:
https://github.com/toptal/crystalball/commit/093294c05463291ed2154dd64b0c3b4c8245fb71#diff-1a523bd9fa0dbf998008b37579210e12L14

![image](https://user-images.githubusercontent.com/9088720/62787610-106c4280-ba93-11e9-824a-9e47a152e0c2.png)

**Comment by pirj** [comment]
Thanks for the heads up. `gh-pages` branch has been rebuilt and the pages were redeployed.
