### ISSUE TITLE
[Documentation] inconsistence with released version

### ISSUE THREAD

**Issue by nyddogghr** [pluff/crystalball#93]
Hi,

While trying your gem, I noticed 2 inconsistences between the documentation and the version of the gem installed by adding `gem 'crystalball'` in the gemfile : 
* The default path is `tmp/execution_maps.yml`, the `s` is missing in the doc;
* The map path in the config file is just `map_path`.

I do know these can be found when looking at [fixtures](https://github.com/toptal/crystalball/blob/v0.5.0/spec/fixtures/crystalball.yml) in version 0.5, the only issue for me is that the doc [here](https://toptal.github.io/crystalball/) references the config for master.

**Comment by pluff** [comment]
Hi, @nyddogghr. Sorry for late answer. Thanks for feedback, we'll fix these issues asap

**Comment by pluff** [comment]
Fixed here: https://github.com/toptal/crystalball/commit/e97ec75b4572fc9da7f198aa9e4581fd2d53a6c2
