### ISSUE TITLE
is there a way to exclude generating the maps for certain specs?

### ISSUE THREAD

**Issue by noralin** [pluff/crystalball#98]
I'm wondering if it's possible to exclude map generation for spec/features/?

**Comment by pluff** [comment]
HI @noralin. Excluding is not supported for now, however you can add it relatively easy for you project by extending `Crystalball::MapGenerator` and using it in your spec helper.
Something like 
```
class MyMapGenerator < Crystalball::MapGenerator
    def refresh_for_case(example, *args)
      return if example.id =~ /\A(\.\/)?spec\/features/
      super
    end
end
```
should work.

**Comment by noralin** [comment]
Great, thank you! Would you like me to close this?

**Comment by pluff** [comment]
I'll close it for now, however, If this feature will get some upvotes we might add support of it out of the box in future.
